platform:
  - x64
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node 6 x64
  - npm install npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm --version
  - node --version
  - npm install
  - npm prune
build_script:
  - npm test
  - npm run dist
artifacts:
  - path: dist\win\*.nupkg
    name: nupkg
  - path: dist\win\RELEASES
    name: releases
  - path: dist\win\*.exe
    name: installer
deploy:
  description: 'Tusk - Refined Evernote desktop app'
  provider: GitHub
  artifact: nupkg, releases, installer
  auth_token:
    secure: vS3PbROPIEs5ZGaeK7vLTojdSbM33G8cLknTV5OBUDt/utMNiBv9UmrZnuNqR96E
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true
shallow_clone: true
